### ISSUE TITLE
Update supported firefox versions

### ISSUE THREAD

**Issue by ferd** [ferd/useragent#2]
With Firefox 20 coming out, if the library isn't updated soon enough it is likely that Firefox 20 will be seen as Firefox 2.

Ideally all versions from 14 to 20 should be added to the lib, with tests to support it.

**Comment by ferd** [comment]
@lpgauth do you guys deploy from a tag at this point? Is it safe for me to put up a 0.1.2 without breaking your dependencies in internal libs?

**Comment by lpgauth** [comment]
@ferd yes, we use tags for all deps. feel free to update :)
